[tool.poetry]
name = "fastapi_template"
version = "2.1.1"
description = "Feature-rich robust FastAPI template"
authors = ["Pavel Kirilin <win10@list.ru>"]
packages = [
    { include = "fastapi_template" },
]
repository = "https://github.com/s3rius/FastAPI-template"
homepage = "https://github.com/s3rius/FastAPI-template"
readme = "README.md"
keywords = [
    "FastAPI",
    "Cookiecutter",
    "Template"
]


[tool.poetry.dependencies]
python = "^3.8"
cookiecutter = "^1.7.3"
pre-commit = "^2.14.0"
termcolor = "^1.1.0"
pygit2 = "^1.6.0"
pydantic = "^1.8.2"
prompt-toolkit = "^3.0.19"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
fastapi_template = "fastapi_template.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
