# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 20.8b0
    hooks:
      - id: black

  - repo: https://gitlab.com/PyCQA/flake8.git
    rev: 3.8.3
    hooks:
      - id: flake8
        args:
          - "--max-line-length=88"
          - "--extend-ignore=E203"
        exclude: >
          (?x)^(
              migrations/.+
          )$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        args:
          - "--strict"
          - "--ignore-missing-imports"
          - "--allow-subclassing-any"
          - "--allow-untyped-calls"
          - "--pretty"
          - "--show-error-codes"
          - "--no-warn-return-any"
          - "--implicit-reexport"
          - "--allow-untyped-decorators"
        exclude: >
          (?x)^(
              migrations/.+
          )$

  - repo: https://github.com/timothycrosley/isort
    rev: 5.4.2
    hooks:
      - id: isort
        args:
          - "-l=88"
          - "--multi-line=3"
          - "--tc"
          - "--up"
          - "--force-grid-wrap=0"
        exclude: >
          (?x)^(
              migrations/.+
          )$
