---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{cookiecutter.kube_name}}
  name: {{cookiecutter.kube_name}}-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{cookiecutter.kube_name}}-app
  template:
    metadata:
      labels:
        app: {{cookiecutter.kube_name}}-app
    spec:
      containers:
        - name: app
          image: {{cookiecutter.project_name}}:latest
          readinessProbe:
            httpGet:
              path: /api/health
              port: api-port
            initialDelaySeconds: 5
            periodSeconds: 10
          {%- if cookiecutter.db_info.name == "sqlite" %}
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              {%- if cookiecutter.enable_migrations == "True" %}
              {%- if cookiecutter.orm in ['sqlalchemy', 'ormar'] %}
              alembic upgrade head &&
              {%- elif cookiecutter.orm == 'tortoise' %}
              aerich upgrade &&
              {%- endif %}
              {%- endif %}
              python -m {{cookiecutter.project_name }}
          {%- endif %}
          env:
            - name: {{cookiecutter.project_name | upper }}_HOST
              value: "0.0.0.0"
            - name: {{cookiecutter.project_name | upper }}_WORKERS_COUNT
              value: "10"
            {%- if cookiecutter.db_info.name not in ["none", "sqlite"] %}
            - name: {{cookiecutter.project_name | upper }}_DB_HOST
              value: "{{cookiecutter.kube_name}}-db-service"
            {%- endif %}
            {%- if cookiecutter.enable_redis == 'True' %}
            - name: {{cookiecutter.project_name | upper }}_REDIS_HOST
              value: "{{cookiecutter.kube_name}}-redis-service"
            {%- endif %}
          resources:
            limits:
              memory: "200Mi"
              cpu: "100m"
          ports:
            - containerPort: 8000
              name: api-port
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{cookiecutter.kube_name}}
  name: {{cookiecutter.kube_name}}-app-service
spec:
  selector:
    app: {{cookiecutter.kube_name}}-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: api-port
      name: api-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{cookiecutter.kube_name}}-app
  namespace: {{cookiecutter.kube_name}}
  labels:
    name: {{cookiecutter.kube_name}}-app
spec:
  rules:
    - host: {{ cookiecutter.kube_name }}.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{cookiecutter.kube_name}}-app-service
                port:
                  name: api-port

---
